#!/bin/sh
set -e

if [ "$1" = "upgrade" ] || [ "$1" = "remove" ]; then
    if [ -L /usr/doc/dnsmasq ]; then
       rm -f /usr/doc/dnsmasq
    fi
fi

if [ -x /usr/sbin/invoke-rc.d ] ; then
    invoke-rc.d dnsmasq  stop || true
else
    /etc/init.d/dnsmasq stop || true
fi

exit 0


