#!/bin/sh

set -e

. debian/tests/helpers

cd debian/tests/`basename $0`.d

#Stop services and networking for configuration
systemctl stop dnsmasq.service
systemctl stop named.service
systemctl stop networking.service

#Add interfaces needed for the test
cat add-to.interfaces >> /etc/network/interfaces

#Configure dnsmasq
cp dnsmasq-autopkgtest.conf /etc/dnsmasq.d/

#Configure bind
cp db.autopkg.test /etc/bind/
cat add-to.named.conf.local >>/etc/bind/named.conf.local
cp named.conf.options /etc/bind/named.conf.options

#Start networking and services
systemctl start networking.service
systemctl start named.service
systemctl start dnsmasq.service

#Get an address on veth1 and check the result
echo ~~~ Get an address on veth1 and check the result...
ip netns exec clientnet ifup veth1
ip netns exec clientnet ip addr show dev veth1 >ip-addr.out 2>&1
cat ip-addr.out
match_or_exit ip-addr.out ip-addr.patterns

#Query some test zone records and check the result
echo ~~~ Query some test zone records and check the result...
ip netns exec clientnet dig +short SOA autopkg.test >dig.out 2>&1
ip netns exec clientnet dig +short NS autopkg.test >>dig.out 2>&1
ip netns exec clientnet dig +short A ns.autopkg.test >>dig.out 2>&1
ip netns exec clientnet dig +short A dhcp3.autopkg.test >>dig.out 2>&1
cat dig.out
if [ `linecount dig.out` -ne `linecount dig.patterns` ] ; then
	error_exit 'empty or unexpected output'
fi
match_or_exit dig.out dig.patterns

#Test dhcp_lease_time and dhcp_release
leases_file='/var/lib/misc/dnsmasq.leases'
client_ip_address=`cut -d' ' -f3 $leases_file`
client_mac_address=`cut -d' ' -f2 $leases_file`
echo ~~~ Test dhcp_lease_time...
if ! dhcp_lease_time $client_ip_address; then
	error_exit "'dhcp_lease_time $client_ip_address' failed with return code $?"
else
	#Add \n to dhcp_lease_time's output
	echo ''
fi
echo ~~~ Test dhcp_release...
cat $leases_file
if ! dhcp_release veth0 $client_ip_address 1-$client_mac_address; then
	error_exit "'dhcp_release veth0 $client_ip_address 1-$client_mac_address' failed with return code $?0"
fi
if [ -n "`cat $leases_file`" ]; then
	cat $leases_file
	error_exit "$leases_file is not empty"
fi

#Done
echo Looks good.
