#!/bin/sh
set -e

# Create the dnsmasq user in dnsmasq-base, so that Dbus doesn't complain.

if [ "$1" = "configure" ]; then
  # Create the user to run as.
  if [ -z "`id -u dnsmasq 2> /dev/null`" ]; then
    useradd --system \
            --gid nogroup \
            --comment dnsmasq \
            --home-dir /var/lib/misc --no-create-home \
            --shell /usr/sbin/nologin \
            dnsmasq
  fi
fi

#DEBHELPER#

